export const KEY_MAPPINGS = [
  { key: 'a', text: 'a' },
  { key: 'b', text: 'b' },
  { key: 'c', text: 'c' },
  { key: 'd', text: 'd' },
  { key: 'e', text: 'e' },
  { key: 'f', text: 'f' },
  { key: 'g', text: 'g' },
  { key: 'h', text: 'h' },
  { key: 'i', text: 'i' },
  { key: 'j', text: 'j' },
  { key: 'k', text: 'k' },
  { key: 'l', text: 'l' },
  { key: 'm', text: 'm' },
  { key: 'n', text: 'n' },
  { key: 'o', text: 'o' },
  { key: 'p', text: 'p' },
  { key: 'q', text: 'q' },
  { key: 'r', text: 'r' },
  { key: 's', text: 's' },
  { key: 't', text: 't' },
  { key: 'u', text: 'u' },
  { key: 'v', text: 'v' },
  { key: 'w', text: 'w' },
  { key: 'x', text: 'x' },
  { key: 'y', text: 'y' },
  { key: 'z', text: 'z' },

  { key: '0', text: '0' },
  { key: '1', text: '1' },
  { key: '2', text: '2' },
  { key: '3', text: '3' },
  { key: '4', text: '4' },
  { key: '5', text: '5' },
  { key: '6', text: '6' },
  { key: '7', text: '7' },
  { key: '8', text: '8' },
  { key: '9', text: '9' },
  
  { key: 'SPACE', text: 'SPACE' },
  { key: '↓', text: '↓' },
  { key: '↓', text: '↓' },
  { key: '←', text: '←' },
  { key: '→', text: '→' },

  // Missing: ESC, ENTER, SHIFT, CMD/CTRL, ALT, TAB, DELETE/BACKSPACE
];
